In [12]:
#from google.colab import drive
#drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('Tnews1.csv')

In [3]:
df.head()

text  label
0  The 8-year-old boy who was killed by Boston Ma...      1
1  Such a tragedy today in Boston, there are no w...      0
2  Disgusting. RT @WBCSays: THANK GOD FOR THE BOS...      1
3  An 8 year old boy was at the finish line waiti...      1
4  Mi preocupación por Boston y Venezuela es dire...      0

In [0]:
#drop NAN values
#df=df.dropna()

In [5]:
#get independent feature
x=df.drop('label',axis=1)

In [6]:
#get dependent feature
y=df['label']

In [7]:
x.shape

(4952, 1)

In [8]:
y.shape

(4952,)

In [9]:
import tensorflow as tf

C:\Users\DSU\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\DSU\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\DSU\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\DSU\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: 

In [10]:
tf.__version__

'2.1.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [12]:
# vocab size
voc_size=5000

In [13]:
#one hot representation
messages=x.copy()

In [14]:
messages.reset_index(inplace=True)

In [0]:
#messages.head()

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DSU\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [17]:
# data preprocessing removing unnecessory words
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()    # for stmeming
corpus = []     # creating a list of corpus 
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['text'][i]) # replace or substituting every hting with a space apart from a-z and A-Z char
    review = re.sub('http[\w:/\.]+',' ', messages['text'][i]) # remove urls
    
    review = review.lower()     #lower all chars
    review = review.split()     # split for removing stopwords
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]   # if words are not in stopwords then stemming
    review = ' '.join(review)   # join the splits
    corpus.append(review)     # append to list corpus

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059


3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707
3708
3709


In [18]:
corpus

['8-year-old boy kill boston marathon blast wait greet runner father.',
 'tragedi today boston, word describ sadness.',
 'disgusting. rt @wbcsays: thank god boston marathon bombs!! westboro baptist church picket funer killed. #praisegod',
 '8 year old boy finish line wait hug father die bomb went off... #prayforboston',
 'mi preocupación por boston venezuela es directament proporcion la somnolencia que cargo en est momento',
 '#screwwestboro breaking: westboro baptist church picket funer dead boston bomb',
 "can't believ one dead 8 year old boy... #whatishappeningtotheworld #prayforboston",
 'boston: altra prova della malignità umana. preghiamo.',
 'westboro baptist church threaten picket funer boston marathon tragedi victims. -states/130415/westboro-baptist-church-threatens-to-picket-boston-marathon-funer …',
 '8 yr old boy kill wait dad finish race. mom & sister also injured. may rip. #prayforboston',
 'lie! mt @hopeforboston: rip 8 yr-old girl die boston, run sandi hook kid #prayfor

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]  # one hot for corpus word and vocab #words of corpus cpnvert in index based on vocab word's index
onehot_repr

[[2078, 688, 4660, 1920, 4314, 2390, 2682, 865, 1853, 3928, 2119, 4636],
 [1575, 1783, 2390, 4970, 4751, 843],
 [4695,
  1299,
  1625,
  3691,
  2848,
  2390,
  2682,
  1221,
  1522,
  3619,
  1445,
  4102,
  3464,
  4551,
  3169],
 [2078,
  688,
  4660,
  1920,
  103,
  3800,
  1853,
  82,
  4636,
  312,
  4563,
  1531,
  507,
  2812],
 [293,
  3985,
  359,
  2390,
  1579,
  3862,
  1142,
  1510,
  1764,
  1874,
  2923,
  512,
  4793,
  1645,
  4017],
 [1915, 1499, 1522, 3619, 1445, 4102, 3464, 749, 2390, 4563],
 [4499, 1602, 3104, 749, 2078, 688, 4660, 1920, 1478, 2812],
 [2390, 2620, 1910, 2738, 376, 772, 2385],
 [1522,
  3619,
  1445,
  3888,
  4102,
  3464,
  2390,
  2682,
  1575,
  3934,
  1606,
  2344,
  1522,
  3619,
  1445,
  1036,
  4261,
  4102,
  2390,
  2682,
  3464,
  679],
 [2078,
  3393,
  4660,
  1920,
  4314,
  1853,
  2044,
  103,
  4654,
  4853,
  3664,
  1799,
  4791,
  2128,
  1394,
  2812],
 [184,
  3256,
  2956,
  1394,
  2078,
  3393,
  4660,
  898,
  312,
  23

In [20]:
# every sentance has different length but we have to supply fixed length sentances to the model so we do pad sequenceing (appending 0 to make all statements equal length)
# embading representation
sent_length=20  # all sentanses length should be 20 words because we are dealing with title only which is short in nature for long text we can expend it.
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # pre means add 0 before the stances 
print(embedded_docs)    # it has all x values

[[   0    0    0 ... 3928 2119 4636]
 [   0    0    0 ... 4970 4751  843]
 [   0    0    0 ... 3464 4551 3169]
 ...
 [   0    0    0 ... 2285 2390 2331]
 [   0    0    0 ...  312 1920 2812]
 [   0    0    0 ... 4754 1647 2390]]


In [21]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0, 2078,  688, 4660,
       1920, 4314, 2390, 2682,  865, 1853, 3928, 2119, 4636])

In [22]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
#model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(64, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                6464      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 262,929
Trainable params: 262,929
Non-trainable params: 0
__________________________________________________

In [23]:
len(embedded_docs),y.shape

(4952, (4952,))

In [24]:
import numpy as np             # convert all data into array so that we can perform further measures
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [25]:
x_final.shape,y_final.shape

((4952, 20), (4952,))

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.30,random_state=42)   # one more parameter---> , random_state=42

In [28]:
y_test.size

1486

In [30]:
#training
model.fit(x_train,y_train,validation_split=0.20,batch_size=32,epochs=4)   #validation_split=0.20  or  validation_data=(x_test,y_test)

Train on 2772 samples, validate on 694 samples
Epoch 1/4
2772/2772 [==============================] - 2s 708us/sample - loss: 0.0653 - accuracy: 0.9830 - val_loss: 0.1132 - val_accuracy: 0.9697
Epoch 2/4
2772/2772 [==============================] - 2s 674us/sample - loss: 0.0336 - accuracy: 0.9906 - val_loss: 0.1181 - val_accuracy: 0.9741
Epoch 3/4
2772/2772 [==============================] - 2s 787us/sample - loss: 0.0189 - accuracy: 0.9960 - val_loss: 0.1049 - val_accuracy: 0.9755
Epoch 4/4
2772/2772 [==============================] - 2s 703us/sample - loss: 0.0136 - accuracy: 0.9971 - val_loss: 0.1512 - val_accuracy: 0.9683


In [31]:
#Performance Metrics And Accuracy
y_pred=model.predict_classes(x_test)


In [32]:
from sklearn.metrics import confusion_matrix,classification_report

In [33]:

report=classification_report(y_test,y_pred)
print(report)
#confusion_matrix(y_test,y_pred)


              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1112
           1       0.96      0.92      0.94       374

    accuracy                           0.97      1486
   macro avg       0.96      0.95      0.96      1486
weighted avg       0.97      0.97      0.97      1486



In [34]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9697173620457604